'use strict';

import 'nodelist-foreach-polyfill';
import elementClosest from 'element-closest';
import "@babel/polyfill";
import 'fetch-polyfill';
import 'ie11-scroll-into-view';
import 'cross-browser-polyfill';
elementClosest(window);

import toggleNumber from './modules/toggleNumber';
import togglePopup from './modules/togglePopup';
import scroll from './modules/scroll';
import toggleRepairTypes from './modules/toggleRepairTypes';
import togglePrivacy from './modules/togglePrivacy';
import toggleFormula from './modules/toggleFormula';
import sliderFormula from './modules/sliderFormula';
import masksNumber from './modules/masksNumber';
import sendForms from './modules/sendForms';
import renderPopup from './modules/renderPopup';
//import mobileFormulaSlider from './modules/mobileFormulaSlider';
import sliderRepair from './modules/sliderRepair';
import tabsWork from './modules/tabsWork';
import accordion from './modules/accordion';
import toggleCosalt from './modules/toggleConsultation';
import sliderPortfolio from './modules/sliderPortfolio';
import sliderRewievs from './modules/sliderRewievs';
import docTabs from './modules/docTabs';
import togglePopupPortfolio from './modules/togglePopupPortfolio';
import sliderPortfolioTwo from './modules/sliderPorfolioTwo';


toggleNumber();
togglePopup();
scroll();
toggleRepairTypes();
togglePrivacy();
toggleFormula();
sliderFormula();
masksNumber();
sendForms();
renderPopup();
//mobileFormulaSlider();
sliderRepair();
tabsWork();
accordion();
toggleCosalt();
sliderPortfolio();
sliderRewievs();
docTabs();
togglePopupPortfolio();
sliderPortfolioTwo();
