'use strict';

import toggleNumber from './modules/toggleNumber';
import togglePopup from './modules/togglePopup';
import scroll from './modules/scroll';
import toggleRepairTypes from './modules/toggleRepairTypes';
import togglePrivacy from './modules/togglePrivacy';
import toggleFormula from './modules/toggleFormula';
import sliderFormula from './modules/sliderFormula';
import masksNumber from './modules/masksNumber';
import sendForms from './modules/sendForms';
import renderPopup from './modules/renderPopup';
//import mobileFormulaSlider from './modules/mobileFormulaSlider';
import sliderRepair from './modules/sliderRepair';
import tabsWork from './modules/tabsWork';
import accordion from './modules/accordion';
import toggleCosalt from './modules/toggleConsultation';

toggleNumber();
togglePopup();
scroll();
toggleRepairTypes();
togglePrivacy();
toggleFormula();
sliderFormula();
masksNumber();
sendForms();
renderPopup();
//mobileFormulaSlider();
sliderRepair();
tabsWork();
accordion();
toggleCosalt();
